### ISSUE TITLE
Thanks for the port -- I think the commit at `e31cd5b` is a bad merge.

### ISSUE THREAD

**Issue by kf6gpe** [technoblogy/ulisp-cardputer#2]
Just an FYI -- it does not compile in the Arduino IDE, which complains about a slew of duplicate symbols. I forked and started trying to clean them up, but ran out of time.

**Comment by technoblogy** [comment]
It sounds like you might have included both the files `ulisp-cardputer-comments.ino` and `ulisp-cardputer.ino`. Just use one of them and see if that solves the problem.

**Comment by kf6gpe** [comment]
Awesome. I don't know what I did wrong with the Arduino IDE (and I'm a bit of a noob with it anyway), but just removing the -comments version of the file fixed the problem.

Thanks!! Now to figure out why the Lisp code I'm trying to compile into the image isn't working (it's not uLisp or your port, it's me being stupid).

Thanks!
